# -*- coding: utf-8 -*-
"""APP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8RBQ_5DHlBI9SrLiDsT5EHOytxJ0ldz
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="FEMA Disaster Relief Dashboard")

st.title("FEMA Disaster Relief Dashboard")
st.write("Author: Rayan Latif")

@st.cache_data
def load_data():
    df = pd.read_csv("fema_disaster_data_small.csv")

    df["repairAmount"] = pd.to_numeric(df["repairAmount"], errors="coerce")
    df["tsaEligible"] = pd.to_numeric(df["tsaEligible"], errors="coerce")
    df = df.dropna(subset=["repairAmount", "tsaEligible"])
    df["tsaEligible"] = df["tsaEligible"].astype(int)

    return df

df = load_data()

st.subheader("Data Preview")
st.write(df.head())

st.subheader("Histogram of Repair Amount")
fig_hist = px.histogram(
    df,
    x="repairAmount",
    nbins=30,
    title="Distribution of Repair Amounts"
)
fig_hist.update_layout(
    xaxis_title="Repair Amount",
    yaxis_title="Count"
)
st.plotly_chart(fig_hist)

st.subheader("Boxplot: Repair Amount by TSA Eligibility")
fig_box = px.box(
    df,
    x="tsaEligible",
    y="repairAmount",
    title="Repair Amount by TSA Eligibility",
    labels={
        "tsaEligible": "TSA Eligible (1 = Yes, 0 = No)",
        "repairAmount": "Repair Amount"
    }
)
st.plotly_chart(fig_box)

st.markdown(
    "In my analysis, TSA-eligible "
    "applicants tended to have higher typical repair amounts and a wider spread of costs."
)
